Add 'list' operation

diff --git a/clashctrl b/clashctrl
--- a/clashctrl
+++ b/clashctrl
@@ -1,6 +1,25 @@
 #!/bin/bash
 set -o nounset
 
+list_help () {
+cat <<EOF
+usage: clashctrl list
+
+List all proxies.
+EOF
+}
+
+list_op () {
+    if test $# -gt 0
+    then
+        >&2 printf "error: too many arguments\n"
+        return 1
+    fi
+    curl -sS -X GET \
+        -H "Content-Type: application/json" \
+        "127.0.0.1:9090/proxies"
+}
+
 get_help () {
 cat <<EOF
 usage: clashctrl get [<selector>]
@@ -70,7 +89,7 @@ usage:
 operation:
     switch          switch current GLOBAL proxy
     get             get current GLOBAL proxy
-    getall          (yet to implement) get all proxies
+    list            list all proxies
     curl            (yet to implement) custom curl
 
 Use clashctrl <operation> --help for more about <operation>.
@@ -112,7 +131,7 @@ main () {
         Help
         exit 0
         ;;
-    switch|get)
+    switch|get|list)
         TryToHelp "$@"
         ${op}_op "$@"
         ;;
